### ISSUE TITLE
Improve sign and verify message output styling

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#150]
#### Sign message

<img width="1134" alt="image" src="https://cloud.githubusercontent.com/assets/8068/25436061/615cf54c-2a92-11e7-8f17-cfa4cdbdd96d.png">

#### Verify message

<img width="1147" alt="image" src="https://cloud.githubusercontent.com/assets/8068/25436068/6cd28df6-2a92-11e7-88b1-c6c3efffa0c7.png">

### Desired appearance

In order to better clarify `input` versus `output` to the user. I propose something like the following which gives a `terminal` feel to them.

```css
textarea {
  color: white;
  background-color: black;
  padding-left: 5px;
  padding-right: 5px;
  border-radius: 5px;
  margin-top: 10px;
  font-family: monospace;
}
```

**Note**: Currently these text areas are editable. We should set them to `readonly`. Alternatively, we can contain them within a `<pre>` element instead.

#### Sign message

<img width="1123" alt="image" src="https://cloud.githubusercontent.com/assets/8068/25436087/7c0f0ede-2a92-11e7-87bd-4e4b258af048.png">

#### Verify message

<img width="1149" alt="image" src="https://cloud.githubusercontent.com/assets/8068/25436092/7fb7f3a2-2a92-11e7-911c-4f257e04213d.png">

### Steps to reproduce

Sign or verify a message using `lisk-nano`.
